# Generated by Django 4.1 on 2022-08-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Blogs',
            },
        ),
    ]
